openapi: 3.0.0
info:
  title: orderstatus
  version: POST
  description: Check Status of Order
  license:
    name: MIT
  contact:
    name: Uday
    email: UGiridhar@softeon.com
servers:
  - url: 'http://localhost:3000'
paths:
  /orderstatus:
    post:
      summary: Fetches Status of the Order
      operationId: post-orderstatus
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              schema:
                type: string
              required: true
            Content-Type:
              schema:
                type: string
              required: true
            Date:
              schema:
                type: string
                format: date-time
              required: true
            Content-Length:
              schema:
                type: number
              required: true
              explode: false
          content:
            application/xml:
              schema:
                type: object
                properties:
                  ORDER_CHANGE_RESPONSE:
                    type: object
                    required:
                      - HEADER
                      - DETAIL
                    properties:
                      HEADER:
                        type: object
                        required:
                          - WAREHOUSE_ID
                          - BUILDING_ID
                          - BUSINESS_UNIT
                          - USER_ID
                        properties:
                          WAREHOUSE_ID:
                            type: string
                            maxLength: 5
                          BUILDING_ID:
                            type: string
                            maxLength: 5
                          BUSINESS_UNIT:
                            type: string
                            maxLength: 5
                          USER_ID:
                            type: string
                            maxLength: 15
                      DETAIL:
                        type: object
                        required:
                          - CODE
                          - MESSAGE
                        properties:
                          CODE:
                            type: string
                            maxLength: 10
                          MESSAGE:
                            type: string
                            maxLength: 50
                required:
                  - ORDER_CHANGE_RESPONSE
              examples:
                Example 1: {}
      parameters:
        - schema:
            type: string
            default: application/xml
          in: header
          name: Content-Type
          required: true
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties:
                ORDER_CHANGE_REQUEST:
                  type: object
                  required:
                    - HEADER
                    - DETAIL
                  properties:
                    HEADER:
                      type: object
                      required:
                        - WAREHOUSE_ID
                        - BUILDING_ID
                        - BUSINESS_UNIT
                        - USER_ID
                        - PASSWORD
                      properties:
                        WAREHOUSE_ID:
                          type: string
                          maxLength: 5
                        BUILDING_ID:
                          type: string
                          maxLength: 5
                        BUSINESS_UNIT:
                          type: string
                          maxLength: 5
                        USER_ID:
                          type: string
                          maxLength: 15
                        PASSWORD:
                          type: string
                          maxLength: 15
                    DETAIL:
                      type: object
                      required:
                        - ORDER_NO
                        - ACTION_TYPE
                      properties:
                        ORDER_NO:
                          type: string
                          maxLength: 20
                        ACTION_TYPE:
                          type: string
                          maxLength: 1
                        ADDRESS_NAME:
                          type: string
                          maxLength: 80
                        ADDRESS1:
                          type: string
                        ADDRESS2:
                          type: string
                          maxLength: 100
                        ADDRESS3:
                          type: string
                          maxLength: 45
                        CITY:
                          type: string
                          maxLength: 45
                        STATE:
                          type: string
                          maxLength: 100
                        ZIP:
                          type: string
                          maxLength: 10
                        ZIP_EXTN:
                          type: string
                          maxLength: 10
                        COUNTRY_CODE:
                          type: string
                          maxLength: 2
                        PHONE:
                          type: string
                          maxLength: 25
                        EMAIL:
                          type: string
                          maxLength: 75
                        CARRIER_CODE:
                          type: string
                          maxLength: 25
                        CARR_DELV_TYPE:
                          type: string
                          maxLength: 25
                        FREIGHT_TYPE:
                          type: string
                          maxLength: 1
                        BILL_ACCOUNT_NO:
                          type: string
                          maxLength: 20
              required:
                - ORDER_CHANGE_REQUEST
components:
  schemas:
    WAREHOUSE_ID:
      title: OrderStatus
      type: object
      properties:
        id:
          type: string
  securitySchemes: {}
